# Generated by Django 4.2.15 on 2024-10-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('diary_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('hint', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
